// Development-only browser tooling. npm install --prefix .tools --save-dev playwright
import { chromium } from '../.tools/node_modules/playwright/index.mjs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { resolve, dirname } from 'node:path';
import { mkdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const output=resolve(root,'Design/Previews');
await mkdir(output,{recursive:true});await mkdir(resolve(root,'.artifacts/motion'),{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1280,height:850},colorScheme:'dark',reducedMotion:'no-preference'});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const url=pathToFileURL(resolve(root,'Design/motion.html')).href;
await page.goto(url+'?manual');
assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(247, 243, 235)');
await page.locator('.handle').hover();await page.waitForTimeout(420);
assert.equal(await page.evaluate(()=>motionPreview.mode),'expanded');
const dictate=page.locator('.rail-row[aria-label="Dictate"]');
await dictate.hover();await page.waitForTimeout(150);
assert.equal(await page.locator('#rail-tooltip').innerText(),'Dictate');
assert.equal(await page.locator('#rail').evaluate(e=>Math.round(e.getBoundingClientRect().width)),56);
assert.equal(await page.locator('#rail-tooltip').evaluate(e=>getComputedStyle(e).pointerEvents),'none');
await page.screenshot({path:resolve(output,'07-icon-rail.png')});
await page.locator('.rail-row[aria-label="Assistant"]').focus();
await page.waitForTimeout(120);
assert.equal(await page.locator('#rail-tooltip').innerText(),'Assistant');
await page.locator('.rail-row[aria-label="Assistant"]').evaluate(e=>e.blur());

await page.mouse.move(100,100);await page.waitForTimeout(720);
assert.equal(await page.evaluate(()=>motionPreview.mode),'idle');
await page.getByRole('button',{name:'Speaking',exact:true}).click();
await page.waitForTimeout(400);
const before=await page.locator('.wave i').evaluateAll(es=>es.map(e=>e.style.height));
await page.waitForTimeout(180);
const after=await page.locator('.wave i').evaluateAll(es=>es.map(e=>e.style.height));
assert.notDeepEqual(before,after,'Speaking must animate');
await page.screenshot({path:resolve(output,'05-motion-speaking.png')});
await page.getByRole('button',{name:'Stop speaking'}).click();
assert.equal(await page.evaluate(()=>motionPreview.mode),'interrupted');
assert((await page.locator('.wave i').evaluateAll(es=>es.map(e=>e.style.height))).every(h=>parseFloat(h)===3));
await page.getByLabel('Reduce motion',{exact:true}).check();
await page.getByRole('button',{name:'Speaking',exact:true}).click();
const reduced=await page.locator('.wave i').evaluateAll(es=>es.map(e=>e.style.height));
await page.waitForTimeout(180);
assert.deepEqual(await page.locator('.wave i').evaluateAll(es=>es.map(e=>e.style.height)),reduced);
assert.equal(await page.locator('#rail').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
await page.getByRole('button',{name:'Meeting prompt',exact:true}).click();
assert(await page.locator('#toast').evaluate(e=>e.classList.contains('visible')));
await page.waitForTimeout(10200);
assert(!(await page.locator('#toast').evaluate(e=>e.classList.contains('visible'))));
assert.equal(await page.evaluate(()=>motionPreview.mode),'idle','Timeout must never record');
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>document.activeElement.id),'walkthrough');
assert.deepEqual(errors,[]);
const mobile=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
const small=await mobile.newPage();await small.goto(url);await small.waitForTimeout(900);
assert.equal(await small.evaluate(()=>motionPreview.playing),false,'Reduced Motion suppresses autoplay');
await small.getByRole('button',{name:'Speaking',exact:true}).click();
assert(await small.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile page must fit');
await mobile.close();await context.close();
console.log('PASS: icon rail width, hover/focus labels, click-through overlays, light appearance, hover open/close, speaking animation, interruption, reduced motion, prompt expiry, keyboard escape, mobile layout.');
const capture=await browser.newContext({viewport:{width:1280,height:850},reducedMotion:'no-preference',recordVideo:{dir:resolve(root,'.artifacts/motion'),size:{width:1280,height:850}}});
const videoPage=await capture.newPage();await videoPage.goto(url+'?manual');
await videoPage.evaluate(()=>{void motionPreview.walkthrough()});
await videoPage.waitForTimeout(14800);
await capture.close();const source=await videoPage.video().path();await browser.close();
execFileSync('ffmpeg',['-y','-i',source,'-vf','fps=30','-c:v','libx264','-crf','20','-pix_fmt','yuv420p','-movflags','+faststart',resolve(output,'06-motion.mp4')],{stdio:'ignore'});
execFileSync('ffmpeg',['-y','-i',source,'-filter_complex','fps=16,scale=960:-1:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=128[p];[s1][p]paletteuse=dither=bayer:bayer_scale=3','-loop','0',resolve(output,'06-motion.gif')],{stdio:'ignore'});
console.log('Saved speaking screenshot, MP4 and GIF to Design/Previews.');
